# Generated by Django 5.2.1 on 2025-06-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('category', models.CharField(default='General', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='blog/images')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
